[package]
name = "bevy_pc_example"
version = "0.1.0"
edition = "2021"
description = "Example for building a PC app with Bevy"
publish = false
license = "MIT OR Apache-2.0"

# PC向けの依存関係を追加
[dependencies]
bevy = "0.12.0"
# wasm向けの依存関係を追加
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
